# HW1

## Multiple Linear Regression

## Importing the libraries

In [4]:
import numpy as np
import matplotlib.pyplot as plt
import pandas as pd

## Importing the dataset

In [5]:
dataset = pd.read_excel('ENB2012_data.xlsx')
X = dataset.iloc[:,:-2].values
y = dataset.iloc[:, -2 :].values
X_wo_norm =X
print(X)
print(y)

[[9.800e-01 5.145e+02 2.940e+02 ... 2.000e+00 0.000e+00 0.000e+00]
 [9.800e-01 5.145e+02 2.940e+02 ... 3.000e+00 0.000e+00 0.000e+00]
 [9.800e-01 5.145e+02 2.940e+02 ... 4.000e+00 0.000e+00 0.000e+00]
 ...
 [6.200e-01 8.085e+02 3.675e+02 ... 3.000e+00 4.000e-01 5.000e+00]
 [6.200e-01 8.085e+02 3.675e+02 ... 4.000e+00 4.000e-01 5.000e+00]
 [6.200e-01 8.085e+02 3.675e+02 ... 5.000e+00 4.000e-01 5.000e+00]]
[[15.55 21.33]
 [15.55 21.33]
 [15.55 21.33]
 ...
 [16.44 17.11]
 [16.48 16.61]
 [16.64 16.03]]


## Encoding categorical data

In [6]:
from sklearn.linear_model import LinearRegression
from sklearn import preprocessing

X_normalized = preprocessing.normalize(X)

print(X_normalized)
lin_reg = LinearRegression()
lin_reg.fit(X_normalized, y)

[[1.62577463e-03 8.53531681e-01 4.87732389e-01 ... 3.31790741e-03
  0.00000000e+00 0.00000000e+00]
 [1.62576344e-03 8.53525808e-01 4.87729033e-01 ... 4.97682687e-03
  0.00000000e+00 0.00000000e+00]
 [1.62574778e-03 8.53517587e-01 4.87724335e-01 ... 6.63570524e-03
  0.00000000e+00 0.00000000e+00]
 ...
 [6.77526625e-04 8.83516575e-01 4.01598443e-01 ... 3.27835464e-03
  4.37113952e-04 5.46392440e-03]
 [6.77523793e-04 8.83512882e-01 4.01596765e-01 ... 4.37112125e-03
  4.37112125e-04 5.46390156e-03]
 [6.77520153e-04 8.83508134e-01 4.01594607e-01 ... 5.46387220e-03
  4.37109776e-04 5.46387220e-03]]


LinearRegression()

## Splitting the dataset into the Training set and Test set

In [7]:
from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(X_normalized, y, test_size = 0.2, random_state = 42)

## Training the Multiple Linear Regression model on the Training set

In [8]:
from sklearn.linear_model import LinearRegression
regressor = LinearRegression()
regressor.fit(X_train, y_train)

LinearRegression()

## Predicting the Test set results

In [9]:
y_pred = regressor.predict(X_test)
np.set_printoptions(precision=2)
print(np.concatenate((y_pred.reshape(len(y_pred),2), y_test.reshape(len(y_test),2)),1))

[[18.42 19.77 16.47 16.9 ]
 [13.83 16.53 13.17 16.39]
 [32.17 32.69 32.82 32.78]
 [35.82 36.6  41.32 46.23]
 [15.17 17.29 16.69 19.76]
 [28.22 30.71 23.8  24.61]
 [24.14 27.01 24.31 25.63]
 [28.05 29.79 28.67 29.62]
 [17.29 19.1  19.52 22.72]
 [27.19 29.55 28.07 34.14]
 [17.56 19.32 18.46 21.53]
 [34.64 35.71 33.08 34.11]
 [27.31 29.8  29.79 29.92]
 [ 8.82 12.33 10.37 13.44]
 [18.03 19.22 17.69 20.82]
 [37.18 37.82 36.95 36.87]
 [37.76 37.99 36.64 37.01]
 [11.66 14.55 12.3  15.24]
 [15.17 17.34 14.7  16.77]
 [34.61 35.77 32.38 33.62]
 [34.58 35.55 28.67 32.43]
 [35.24 36.37 41.4  45.29]
 [11.04 14.6  11.7  13.88]
 [29.6  31.81 36.86 34.25]
 [12.73 15.38 15.37 19.18]
 [29.56 31.87 35.89 43.3 ]
 [33.96 34.8  36.57 35.39]
 [34.46 35.75 28.91 29.64]
 [14.66 17.15 17.5  21.13]
 [15.78 18.04 13.99 14.35]
 [ 8.22 12.14 10.42 13.39]
 [11.16 14.59 12.3  15.44]
 [14.99 17.27 16.93 20.03]
 [30.82 33.03 26.84 30.17]
 [28.82 31.89 35.94 43.33]
 [27.95 29.95 28.18 30.18]
 [31.77 32.89 32.72 33.78]
 

In [10]:
from sklearn.metrics import r2_score
average=r2_score(y_test,y_pred)
y1_r2= r2_score(y_test[:,0],y_pred[:,0])
y2_r2 =r2_score(y_test[:,1],y_pred[:,1])
print(average,y1_r2,y2_r2)

0.9030258683831562 0.913844125587917 0.8922076111783953


In [11]:
from sklearn.metrics import mean_squared_error
mean_squared_error(y_test,y_pred)

9.483989633088544

##Now we predicting a new result with Polynomial Regression


In [12]:
from sklearn.preprocessing import PolynomialFeatures
poly_reg = PolynomialFeatures(degree = 3)
X_poly_train = poly_reg.fit_transform(X_train)
lin_reg_2 = LinearRegression()
lin_reg_2.fit(X_poly_train, y_train)
X_test_poly = poly_reg.fit_transform(X_test)
y_pred_poly = lin_reg_2.predict(X_test_poly)

now check answers

In [13]:
from sklearn.metrics import r2_score
average_poly=r2_score(y_test,y_pred_poly)
y1_poly_r2= r2_score(y_test[:,0],y_pred_poly[:,0])
y2_poly_r2 =r2_score(y_test[:,1],y_pred_poly[:,1])
print(average_poly ,y1_poly_r2,y2_poly_r2)

0.9843622255963262 0.9976416071226276 0.9710828440700248


In [14]:
from sklearn.metrics import mean_squared_error
mean_squared_error(y_test,y_pred_poly)

1.4626023689377026

###now caculating without normalizing

In [15]:
from sklearn.model_selection import train_test_split
X_train_2, X_test_2, y_train_2, y_test_2 = train_test_split(X_wo_norm , y, test_size = 0.2, random_state = 42)

In [16]:
from sklearn.linear_model import LinearRegression
regressor_wo_norm = LinearRegression()
regressor_wo_norm.fit(X_train_2, y_train_2)

LinearRegression()

In [17]:
y_pred_2 = regressor_wo_norm.predict(X_test_2)
np.set_printoptions(precision=2)
print(np.concatenate((y_pred_2.reshape(len(y_pred_2),2), y_test_2.reshape(len(y_test_2),2)),1))

[[18.85 19.83 16.47 16.9 ]
 [14.02 16.92 13.17 16.39]
 [31.31 32.11 32.82 32.78]
 [35.87 36.81 41.32 46.23]
 [15.31 17.36 16.69 19.76]
 [28.58 31.23 23.8  24.61]
 [25.03 27.69 24.31 25.63]
 [28.08 29.86 28.67 29.62]
 [17.73 19.42 19.52 22.72]
 [27.59 30.02 28.07 34.14]
 [18.05 19.65 18.46 21.53]
 [34.27 35.68 33.08 34.11]
 [27.71 30.22 29.79 29.92]
 [ 8.5  12.42 10.37 13.44]
 [18.57 19.55 17.69 20.82]
 [36.87 37.83 36.95 36.87]
 [37.47 37.99 36.64 37.01]
 [11.31 14.61 12.3  15.24]
 [15.25 17.73 14.7  16.77]
 [34.24 35.73 32.38 33.62]
 [34.41 35.63 28.67 32.43]
 [35.3  36.6  41.4  45.29]
 [10.93 14.81 11.7  13.88]
 [29.89 32.26 36.86 34.25]
 [12.5  15.17 15.37 19.18]
 [29.86 32.32 35.89 43.3 ]
 [33.39 34.48 36.57 35.39]
 [34.31 35.8  28.91 29.64]
 [14.71 17.2  17.5  21.13]
 [15.73 17.78 13.99 14.35]
 [ 7.9  12.26 10.42 13.39]
 [10.82 14.65 12.3  15.44]
 [15.1  17.32 16.93 20.03]
 [30.97 33.35 26.84 30.17]
 [29.16 32.33 35.94 43.33]
 [28.01 29.97 28.18 30.18]
 [31.   32.24 32.72 33.78]
 

In [18]:
from sklearn.metrics import r2_score
average_3=r2_score(y_test_2,y_pred_2)
y1_r2_3= r2_score(y_test_2[:,0],y_pred_2[:,0])
y2_r2_3 =r2_score(y_test_2[:,1],y_pred_2[:,1])
print(average_3,y1_r2_3,y2_r2_3)

0.9028963100022006 0.9120062665636756 0.8937863534407257


In [19]:
from sklearn.metrics import mean_squared_error
mean_squared_error(y_test_2,y_pred_2)

9.506630922228643

##Now we predicting a new result with Polynomial Regression WO normalaizing


In [20]:
from sklearn.preprocessing import PolynomialFeatures
poly_reg_2 = PolynomialFeatures(degree = 3)
X_poly_train_wo_norm = poly_reg_2.fit_transform(X_train_2)
lin_reg_4 = LinearRegression()
lin_reg_4.fit(X_poly_train_wo_norm , y_train_2)
X_test_poly_wo_norm = poly_reg_2.fit_transform(X_test_2)
y_pred_poly_wo_norm = lin_reg_4.predict(X_test_poly)

now check answers

In [21]:
from sklearn.metrics import r2_score
average_poly_wo_norm=r2_score(y_test,y_pred_poly_wo_norm)
y1_poly_wo_norm_r2= r2_score(y_test[:,0],y_pred_poly_wo_norm[:,0])
y2_poly_wo_norm_r2 =r2_score(y_test[:,1],y_pred_poly_wo_norm[:,1])
print(average_poly_wo_norm ,y1_poly_wo_norm_r2,y2_poly_wo_norm_r2)

-530585991.81569517 -1042224611.383392 -18947372.247998517


In [22]:
from sklearn.metrics import mean_squared_error
mean_squared_error(y_test,y_pred_poly_wo_norm)

55194596806.20246