# Q5

## Importing the libraries

In [68]:
import numpy as np
import matplotlib.pyplot as plt
import pandas as pd

## Importing the dataset

In [69]:
dataset = pd.read_csv('quality_test.csv')
X = dataset.iloc[ : , :-1].values
y = dataset.iloc[ : , -1].values
print(X)

[[ 0.051267   0.69956  ]
 [-0.092742   0.68494  ]
 [-0.21371    0.69225  ]
 [-0.375      0.50219  ]
 [-0.51325    0.46564  ]
 [-0.52477    0.2098   ]
 [-0.39804    0.034357 ]
 [-0.30588   -0.19225  ]
 [ 0.016705  -0.40424  ]
 [ 0.13191   -0.51389  ]
 [ 0.38537   -0.56506  ]
 [ 0.52938   -0.5212   ]
 [ 0.63882   -0.24342  ]
 [ 0.73675   -0.18494  ]
 [ 0.54666    0.48757  ]
 [ 0.322      0.5826   ]
 [ 0.16647    0.53874  ]
 [-0.046659   0.81652  ]
 [-0.17339    0.69956  ]
 [-0.47869    0.63377  ]
 [-0.60541    0.59722  ]
 [-0.62846    0.33406  ]
 [-0.59389    0.005117 ]
 [-0.42108   -0.27266  ]
 [-0.11578   -0.39693  ]
 [ 0.20104   -0.60161  ]
 [ 0.46601   -0.53582  ]
 [ 0.67339   -0.53582  ]
 [-0.13882    0.54605  ]
 [-0.29435    0.77997  ]
 [-0.26555    0.96272  ]
 [-0.16187    0.8019   ]
 [-0.17339    0.64839  ]
 [-0.28283    0.47295  ]
 [-0.36348    0.31213  ]
 [-0.30012    0.027047 ]
 [-0.23675   -0.21418  ]
 [-0.06394   -0.18494  ]
 [ 0.062788  -0.16301  ]
 [ 0.22984   -0.41155  ]


## Splitting the dataset into the Training set and Test set

In [70]:
from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size = 0.25, random_state = 0)

In [71]:
print(X_train)

[[ 0.13767    0.57529  ]
 [ 0.59274   -0.7405   ]
 [-0.20795    0.17325  ]
 [ 0.29896    0.61915  ]
 [-0.375      0.50219  ]
 [-0.081221   1.1089   ]
 [-0.39804    0.034357 ]
 [-0.21947   -0.016813 ]
 [ 0.63882    0.88962  ]
 [-0.50749    0.90424  ]
 [-0.83007    0.31213  ]
 [ 0.44297    0.67032  ]
 [ 0.82316    0.66301  ]
 [ 0.46601   -0.41886  ]
 [ 0.67339   -0.53582  ]
 [-0.17339    0.69956  ]
 [ 0.52938   -0.5212   ]
 [ 0.50634    0.75804  ]
 [-0.46717   -0.13377  ]
 [ 0.39689    0.82383  ]
 [ 0.28744   -0.76974  ]
 [ 0.22408    0.77997  ]
 [-0.092742   0.68494  ]
 [ 0.10311    0.77997  ]
 [ 0.64459   -0.14108  ]
 [ 0.48329   -0.18494  ]
 [-0.51325    0.46564  ]
 [ 0.322      0.5826   ]
 [-0.046659   0.81652  ]
 [-0.092742   0.55336  ]
 [ 0.2932    -0.2288   ]
 [ 0.062788  -0.16301  ]
 [-0.52477    0.2098   ]
 [-0.20795    0.35599  ]
 [-0.61118   -0.067982 ]
 [ 0.82316    0.27558  ]
 [ 0.051267   0.69956  ]
 [-0.36348    0.31213  ]
 [-0.13882    0.54605  ]
 [-0.43836    0.21711  ]


In [72]:
print(y_train)

[1 0 1 0 1 0 1 1 0 0 0 1 0 0 1 1 1 0 0 0 0 0 1 0 1 1 1 1 1 1 1 1 1 1 0 0 1
 1 1 1 1 1 1 0 1 0 0 1 0 1 0 1 1 1 0 0 0 0 0 0 1 0 0 0 1 1 0 0 1 0 1 0 0 1
 0 0 0 0 1 1 0 1 0 0 0 0 1 1]


In [73]:
print(X_test)

[[-0.75518    0.2902   ]
 [-0.69758    0.041667 ]
 [-0.10426    0.99196  ]
 [ 0.016705  -0.40424  ]
 [-0.38076    0.91886  ]
 [-0.59389    0.005117 ]
 [-0.30588   -0.19225  ]
 [ 0.38537   -0.56506  ]
 [ 0.57546    0.26827  ]
 [ 0.93836    0.012427 ]
 [-0.28283    0.47295  ]
 [-0.59965   -0.41886  ]
 [-0.21371    0.69225  ]
 [-0.0063364  0.39985  ]
 [ 0.63265   -0.030612 ]
 [ 0.79435   -0.55775  ]
 [-0.26555    0.96272  ]
 [ 0.46025    0.012427 ]
 [-0.74366   -0.25804  ]
 [ 0.51786   -0.5943   ]
 [ 0.61578    0.7288   ]
 [-0.046659  -0.57968  ]
 [ 0.16647    0.53874  ]
 [-0.11578   -0.39693  ]
 [-0.66302   -0.21418  ]
 [ 0.73675   -0.18494  ]
 [ 0.60426    0.59722  ]
 [ 0.85196   -0.36769  ]
 [ 0.46601   -0.53582  ]
 [-0.72062    0.53874  ]]


In [74]:
print(y_test)

[0 0 0 1 0 1 1 1 1 0 1 0 1 1 0 0 1 1 0 0 0 0 1 1 0 1 0 0 1 0]


## Feature Scaling

In [75]:
from sklearn.preprocessing import StandardScaler
sc = StandardScaler()
X_train = sc.fit_transform(X_train)
X_test = sc.transform(X_test)

In [76]:
print(X_train)

[[ 0.16475493  0.68440791]
 [ 1.11848143 -1.85627026]
 [-0.55958848 -0.09189701]
 [ 0.50278325  0.76909782]
 [-0.9096885   0.54325805]
 [-0.29399241  1.71476327]
 [-0.95797526 -0.36008754]
 [-0.58373187 -0.45889244]
 [ 1.21505497  1.2913523 ]
 [-1.18735836  1.31958228]
 [-1.863415    0.17626841]
 [ 0.8045965   0.86790273]
 [ 1.60139101  0.85378774]
 [ 0.85288326 -1.23521087]
 [ 1.28750607 -1.46105065]
 [-0.48715833  0.92436267]
 [ 0.98569283 -1.43282068]
 [ 0.93740606  1.03728256]
 [-1.10285652 -0.68472642]
 [ 0.70802296  1.16431743]
 [ 0.47863987 -1.9127302 ]
 [ 0.34585126  1.07962752]
 [-0.31813789  0.8961327 ]
 [ 0.09232478  1.07962752]
 [ 1.22714762 -0.69884141]
 [ 0.88909834 -0.78353132]
 [-1.19943005  0.47268312]
 [ 0.55107001  0.69852289]
 [-0.22155807  1.15020245]
 [-0.31813789  0.64206295]
 [ 0.49071156 -0.86822124]
 [ 0.00781874 -0.74118637]
 [-1.22357343 -0.02132208]
 [-0.55958848  0.26095833]
 [-1.40466977 -0.55769541]
 [ 1.60139101  0.10569348]
 [-0.01632673  0.92436267]
 

In [77]:
print(X_test)

[[-1.70646205  0.13392346]
 [-1.58574514 -0.34597255]
 [-0.34227708  1.48896211]
 [-0.08876108 -1.2069809 ]
 [-0.92176019  1.34781225]
 [-1.36843373 -0.41654748]
 [-0.7648282  -0.79764631]
 [ 0.68387958 -1.51751059]
 [ 1.08226636  0.0915785 ]
 [ 1.84282484 -0.40243249]
 [-0.71652047  0.4867981 ]
 [-1.38050542 -1.23521087]
 [-0.57166017  0.91024768]
 [-0.13705078  0.34564825]
 [ 1.202124   -0.48553713]
 [ 1.5410116  -1.50339561]
 [-0.6803054   1.43250216]
 [ 0.84081157 -0.40243249]
 [-1.68231867 -0.92468118]
 [ 0.96154944 -1.57397054]
 [ 1.1667682   0.98082261]
 [-0.22155807 -1.54574057]
 [ 0.22511338  0.61383298]
 [-0.36642046 -1.19286592]
 [-1.51331499 -0.83999127]
 [ 1.42029468 -0.78353132]
 [ 1.14262482  0.72675287]
 [ 1.66174947 -1.13640597]
 [ 0.85288326 -1.46105065]
 [-1.63403191  0.61383298]]


# train KNN model 1 K= range(1,20) with manhattan

## Training the K-NN model on the Training set

In [144]:
from sklearn.neighbors import KNeighborsClassifier
from sklearn.metrics import confusion_matrix, accuracy_score
from sklearn.metrics import precision_score
from sklearn.metrics import recall_score
for i in range(1 ,20):
  classifier = KNeighborsClassifier(n_neighbors = i , p = 1)
  classifier.fit(X_train, y_train)
  y_pred = classifier.predict(X_test)
  print( "k = ",i, ' accuracy_score =  %.3f    precision_score =  %.3f   recall_score =   %.3f '
       %(accuracy_score(y_test, y_pred),precision_score(y_test, y_pred),recall_score(y_test, y_pred)))

k =  1  accuracy_score =  0.800    precision_score =  0.833   recall_score =   0.714 
k =  2  accuracy_score =  0.767    precision_score =  0.889   recall_score =   0.571 
k =  3  accuracy_score =  0.633    precision_score =  0.615   recall_score =   0.571 
k =  4  accuracy_score =  0.700    precision_score =  0.857   recall_score =   0.429 
k =  5  accuracy_score =  0.767    precision_score =  0.769   recall_score =   0.714 
k =  6  accuracy_score =  0.733    precision_score =  0.875   recall_score =   0.500 
k =  7  accuracy_score =  0.767    precision_score =  0.769   recall_score =   0.714 
k =  8  accuracy_score =  0.833    precision_score =  0.909   recall_score =   0.714 
k =  9  accuracy_score =  0.767    precision_score =  0.684   recall_score =   0.929 
k =  10  accuracy_score =  0.767    precision_score =  0.733   recall_score =   0.786 
k =  11  accuracy_score =  0.800    precision_score =  0.722   recall_score =   0.929 
k =  12  accuracy_score =  0.833    precision_score 

# train KNN model 1 K= range(1,20) with manhattan

## Training the K-NN model on the Training set

In [146]:
from sklearn.neighbors import KNeighborsClassifier
from sklearn.metrics import confusion_matrix, accuracy_score
from sklearn.metrics import precision_score
from sklearn.metrics import recall_score
from sklearn.model_selection import KFold
from sklearn.model_selection import cross_val_score
from numpy import mean
from numpy import std
cv = KFold(n_splits=10, random_state=1, shuffle=True)
for i in range(1 ,20):
  classifier = KNeighborsClassifier(n_neighbors = i , p = 1)
  scores = cross_val_score(classifier, X, y, scoring='accuracy', cv=cv, n_jobs=-1)
  classifier.fit(X_train, y_train)
  y_pred = classifier.predict(X_test)
  print( "k = ",i, ' accuracy_score =  %.3f    precision_score =  %.3f   recall_score =   %.3f '
       %(accuracy_score(y_test, y_pred),precision_score(y_test, y_pred),recall_score(y_test, y_pred)))
  print('Accuracy: %.3f (%.3f)' % (mean(scores), std(scores)))

k =  1  accuracy_score =  0.800    precision_score =  0.833   recall_score =   0.714 
Accuracy: 0.678 (0.138)
k =  2  accuracy_score =  0.767    precision_score =  0.889   recall_score =   0.571 
Accuracy: 0.694 (0.110)
k =  3  accuracy_score =  0.633    precision_score =  0.615   recall_score =   0.571 
Accuracy: 0.746 (0.082)
k =  4  accuracy_score =  0.700    precision_score =  0.857   recall_score =   0.429 
Accuracy: 0.746 (0.090)
k =  5  accuracy_score =  0.767    precision_score =  0.769   recall_score =   0.714 
Accuracy: 0.788 (0.094)
k =  6  accuracy_score =  0.733    precision_score =  0.875   recall_score =   0.500 
Accuracy: 0.720 (0.107)
k =  7  accuracy_score =  0.767    precision_score =  0.769   recall_score =   0.714 
Accuracy: 0.720 (0.101)
k =  8  accuracy_score =  0.833    precision_score =  0.909   recall_score =   0.714 
Accuracy: 0.720 (0.114)
k =  9  accuracy_score =  0.767    precision_score =  0.684   recall_score =   0.929 
Accuracy: 0.754 (0.116)
k =  10  a